name: zero_adventures
description: "A CYOA GAME YOU NEVER KNEW YOU NEEDED"

publish_to: 'none' 


version: 1.0.0

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/stories/interstellar_odyssey.json
    - lib/assets/stories/the_lost_temple_of_zara.json
    - lib/assets/stories/cybernetic_dreams.json
    - lib/assets/stories/the_gilded_cage.json
    - lib/assets/stories/the_alchemists_secret.json
    - lib/assets/stories/echoes_of_the_void.json
    - lib/assets/stories/the_last_stand.json
    - lib/assets/stories/jesters_gambit.json
    - lib/assets/stories/the_crimson_affair.json
    - lib/assets/stories/shadows_of_the_past.json
    - lib/assets/stories/the_ronins_path.json
    - lib/assets/stories/whispers_of_the_heart.json